### ISSUE TITLE
MDARC Incorporation

### ISSUE THREAD

**Issue by grantbow** [prager/MDARC-Dev#1]
README.md says "It is expected that in the near future the Membership Portal will be incorporated into the main MDARC website at https://mdarc.org/" - Is it not fully incorporated yet?

73

**Comment by prager** [comment]
> README.md says "It is expected that in the near future the Membership Portal will be incorporated into the main MDARC website at https://mdarc.org/" - Is it not fully incorporated yet?
> 
> 73

Not really, because the Portal is a standalone application separate from https://www.mdarc.org

**Comment by grantbow** [comment]
It actually seems this is not yet completed in some ways.
